export const ACTION_TYPE = {
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_ERROR: "FETCH_CATEGORIES_ERROR",
  FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_ERROR: "FETCH_PRODUCTS_ERROR",
  CLEAR_FILTER: "CLEAR_FILTER",
  SET_FILTER_CATEGORY: "SET_FILTER_CATEGORY",
  SET_PRICE_SORT: "SET_PRICE_SORT",
  SET_RATING_FILTER: "SET_RATING_FILTER",
  SET_CART: "SET_CART",
  SET_WISHLIST: "SET_WISHLIST",
};
